[build]
command = "react-router build"
publish = "build/client"
environment = { NODE_VERSION = "22.9.0" }

[dev]
command = "react-router dev"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200